spring:
  application:
    name: scrum-aggregator
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:}

file:
  static-data: ${FILE_STATIC:}
  output: ${FILE_OUTPUT:}

pv:
  value: ${PV_VALUE:}
offset:
  days: ${OFFSET_DAY}